# Generated by Django 5.2 on 2025-04-25 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_subject_color_alter_subject_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('initial_date', models.DateField(verbose_name='Initial Date')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('skipped', 'Ignorada')], default='pending', max_length=10)),
                ('review_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reviews.reviewinfo')),
            ],
        ),
    ]
