# Generated by Django 5.2 on 2025-06-19 18:17

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewinfo_notes_alter_reviewinfo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='initial_date',
            field=models.DateField(validators=[reviews.validators.initial_date_validator], verbose_name='Initial Date'),
        ),
    ]
